const GOOGLE_CLIENT_ID =
  process.env.GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET =
  process.env.GOOGLE_CLIENT_SECRET;
const CALLBACK_URL =
  process.env.CALLBACK_URL;
const SESSION_SECRET =
  process.env.SESSION_SECRET;

module.exports = {
    GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET,
    CALLBACK_URL,
    SESSION_SECRET
}